[package]
name = "timefusion"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
datafusion = "46.0.0"
arrow = "54.2.0"
uuid = { version = "1.13", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_arrow = { version = "0.13.1", features = ["arrow-54"] }
serde_json = "1.0.138"
async-trait = "0.1.86"
env_logger = "0.11.6"
log = "0.4.25"
color-eyre = "0.6.3"
arrow-schema = "54.1.0"
regex = "1.11.1"
deltalake = { version = "0.25.0", features = ["datafusion", "s3"] }
delta_kernel = { version = "0.8.0", features = [
  "arrow-conversion",
  "default-engine",
] }
chrono = "0.4.39"
pgwire = "0.28.0"
futures = "0.3.31"
bytes = "1.4"
tokio-rustls = "0.26.1"
sled = "0.34.7"
actix-web = "4.9.0"
# datafusion-postgres = { git = "https://github.com/apitoolkit/FusionGate.git" }
datafusion-postgres = { git = "https://github.com/apitoolkit/datafusion-postgres.git", branch = "insert-query-compliance" }
# datafusion-postgres = { path = "../datafusion-projects/datafusion-postgres/datafusion-postgres/" }
datafusion-functions-json = "0.46.0"
anyhow = "1.0.95"
tokio-util = "0.7.13"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
dotenv = "0.15.0"
task = "0.0.1"
sqlparser = "0.55.0"
rustls-pemfile = "2.2.0"
rustls = "0.23.23"
actix-service = "2.0.2"
lazy_static = "1.5.0"
bcrypt = "0.17.0"
opentelemetry = "0.28.0"
opentelemetry-otlp = "0.28.0"
tracing-opentelemetry = "0.29.0"
bincode = "1.3.3"
opentelemetry_sdk = { version = "0.28.0", features = [
  "experimental_async_runtime",
] }
actix-files = "0.6.6"
datafusion-uwheel = { git = "https://github.com/apitoolkit/datafusion-uwheel.git", branch = "datafusion-46" }
sqllogictest = { git = "https://github.com/risinglightdb/sqllogictest-rs.git" }
criterion = { version = "0.5.1", features = ["async"] }
tempfile = "3.18.0"
aws-config = { version = "1.6.0", features = ["behavior-version-latest"] }
aws-types = "1.3.6"
aws-sdk-s3 = "1.3.0"
url = "2.5.4"
datafusion-common = "46.0.0"

[dev-dependencies]
serial_test = "3.2.0"
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
scopeguard = "1.2.0"
rand = "0.8.5"

[features]
default = []
test = []
