[package]
name = "timefusion"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48", features = ["full"] }
datafusion = "50.3.0"
arrow = "56.2.0"
arrow-json = "56.2.0"
uuid = { version = "1.17", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_arrow = { version = "0.13.4", features = ["arrow-55"] }
serde_json = "1.0.141"
serde_with = "3.14"
serde_yaml = "0.9"
async-trait = "0.1.86"
env_logger = "0.11.6"
log = "0.4.27"
color-eyre = "0.6.5"
arrow-schema = "56.2.0"
regex = "1.11.1"
# Updated so we can use 0.16 kernel version which fixes the json writes error
deltalake = { git = "https://github.com/delta-io/delta-rs.git", rev = "18f949efba220f9b6840a3a991e6d0726198fa18", features = [
  "datafusion",
  "s3",
] }
# deltalake = { version = "0.28.1", features = ["datafusion", "s3"] }
delta_kernel = { version = "0.19.0", features = [
  "arrow-conversion",
  "default-engine-rustls",
  "arrow-56",
] }
chrono = { version = "0.4.39", features = ["serde"] }
chrono-tz = "0.10"
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "postgres",
  "chrono",
  "uuid",
] }
futures = { version = "0.3.31", features = ["alloc"] }
bytes = "1.4"
tokio-rustls = "0.26.1"
datafusion-postgres = "0.12.2"
datafusion-functions-json = "0.50.0"
datafusion_pg_catalog = { git = "https://github.com/ybrs/pg_catalog" }
anyhow = "1.0.100"
tokio-util = "0.7.17"
tokio-stream = { version = "0.1.17", features = ["net"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
tracing = "0.1.44"
tracing-opentelemetry = "0.32"
opentelemetry = "0.31"
opentelemetry-otlp = { version = "0.31", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio"] }
datafusion-tracing = { git = "https://github.com/datafusion-contrib/datafusion-tracing.git", rev = "dd16f3b3af141f1a59ff1cf3721dfea4818adfd5" }
instrumented-object-store = { git = "https://github.com/datafusion-contrib/datafusion-tracing.git", rev = "dd16f3b3af141f1a59ff1cf3721dfea4818adfd5" }
dotenv = "0.15.0"
include_dir = "0.7"
aws-config = { version = "1.6.0", features = ["behavior-version-latest"] }
aws-types = "1.3.6"
aws-sdk-s3 = "1.3.0"
aws-sdk-dynamodb = "1.3.0"
url = "2.5.4"
tokio-cron-scheduler = "0.15"
object_store = "0.12.3"
foyer = { version = "0.21.1", features = ["serde"] }
ahash = "0.8"
lru = "0.16.1"
serde_bytes = "0.11.19"
dashmap = "6.1"
tdigests = "1.0"
bincode = "2.0"

[dev-dependencies]
sqllogictest = { git = "https://github.com/risinglightdb/sqllogictest-rs.git" }
serial_test = "3.2.0"
datafusion-common = "50.3.0"
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
scopeguard = "1.2.0"
rand = "0.9.2"

[features]
default = []
test = []
